alias b='brew'
alias bi='brew install'
alias bs='brew services'
alias bsl='brew services list'
alias bsrm='brew services run mongodb-community'
alias bsrp='brew services run postgresql'
alias bsrr='brew services run redis'
alias bssa='brew services stop --all'
alias bu='brew uninstall'
alias bupgr='brew upgrade && brew upgrade --cask && brew cleanup && brew doctor'

alias caski='brew install --cask'
alias casku='brew uninstall --cask'
