alias b='brew'
alias bi='brew install'
alias bs='brew services'
alias bsl='brew services list'
alias bsrm='brew services run mongodb-community'
alias bsrp='brew services run postgresql'
alias bsrr='brew services run redis'
alias bssa='brew services stop --all'
alias bu='brew uninstall'
alias bupgr='brew upgrade && cask upgrade && brew cleanup && brew doctor'

alias cask='brew --cask'
alias caski='cask install'
alias casku='cask uninstall'
