alias be='bundle exec'
alias ber='bundle exec rails'
alias berc='bundle exec rails c'
alias berdbm='bundle exec rake db:migrate'
alias berdbr='bundle exec rake db:reset'
alias berdbro='bundle exec rake db:rollback'
alias berdbs='bundle exec rake db:setup'
alias bergm='bundle exec rails g migration'
alias berk='bundle exec rake'
alias bers='bundle exec rails s'

alias dcrb='docker-compose run --rm app bundle'
alias dcrgm='docker-compose run --rm app rails generate migration'
alias dcrr='docker-compose run --rm app rails'
alias dcrrc='docker-compose run --rm app rails c'
alias dcrs='docker-compose run --rm app rspec'

alias gi='gem install'
alias gu='gem uninstall'
