alias ya='yarn add'
alias yg='yarn global'
alias yga='yarn global add'
alias ygr='yarn global remove'
alias ygu='yarn global upgrade'
alias yr='yarn remove'
alias ys='yarn start'
alias yu='yarn upgrade'
